name: moviesapp
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9
  bloc: ^4.0.0
  rxdart: ^0.24.1
  eva_icons_flutter: ^2.0.0
  flutter_rating_bar: ^3.0.1+1
  page_indicator: ^0.3.0
  font_awesome_flutter: ^8.8.1
  sliver_fab: ^1.0.0
  youtube_player_flutter: ^7.0.0+3
  meet_network_image: ^0.1.2
  flutter_bloc: ^4.0.0
  cupertino_icons: ^0.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  fonts:
    - family: ProductSans
      fonts:
        - asset: fonts/ProductSans-Bold.ttf
          weight: 900
        - asset: fonts/ProductSans-Light.ttf
          weight: 400
        - asset: fonts/ProductSans-BlackItalic.ttf
          style: italic
          weight: 900